apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: nvv4orzfq-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/nvv4orzfq-java-springboot-gitops